trigger:
- main  # Adjust as needed

pr:
- '*'

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self  # Checkout the primary repository

- script: |
    echo "==== Current working directory ===="
    cd
    echo "==== Directory contents ===="
    dir

    echo "Fetching the latest commit from the feature branch..."
    echo "Source branch: %SYSTEM_PULLREQUEST_SOURCEBRANCH%"
    set source_branch=%SYSTEM_PULLREQUEST_SOURCEBRANCH:refs/heads/=%
    echo "Stripped source branch: %source_branch%"

    if "%source_branch%"=="" (
      echo "Error: Source branch is empty."
      exit /b 1
    )

    echo "Fetching the latest commit from the feature branch..."
    git fetch origin %source_branch% || (echo "Error: Failed to fetch source branch" && exit /b 1)
    git log -1 --pretty=format:"%%H" FETCH_HEAD > latest_commit.txt || (echo "Error: Failed to get latest commit ID from source branch" && exit /b 1)

    echo "Contents of latest_commit.txt:"
    type latest_commit.txt || (echo "Error: latest_commit.txt not found or empty" && exit /b 1)

    set /p latest_commit=<latest_commit.txt
    echo Latest commit ID from feature branch: %latest_commit%

    echo "Running Gitleaks..."
    gitleaks detect --commit=%latest_commit% || (echo "Error: Gitleaks command failed" && exit /b 1)
  displayName: 'Fetch latest commit from feature branch and run Gitleaks'
  env:
    GITLEAKS_VERSION: 'latest'
