trigger:
- main  # Adjust as needed

pr:
- '*'

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self  # Checkout the primary repository

- script: |
    echo "==== Current working directory ===="
    cd
    echo "==== Directory contents ===="
    dir

    echo "Fetching the latest commit in the repository..."
    git fetch --all
    git log -1 --pretty=format:"%H" > latest_commit.txt || (echo "Error: Failed to get latest commit ID" && exit /b 1)

    echo "Contents of latest_commit.txt:"
    type latest_commit.txt || (echo "Error: latest_commit.txt not found or empty" && exit /b 1)

    set /p latest_commit=<latest_commit.txt
    echo Latest commit ID: %latest_commit%

    echo "Running Gitleaks..."
    gitleaks detect --commit=%latest_commit% || (echo "Error: Gitleaks command failed" && exit /b 1)
  displayName: 'Fetch latest commit and run Gitleaks'
  env:
    GITLEAKS_VERSION: 'latest'
