trigger:
- main  # or your default branch

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'  # or the .NET version you need
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    trigger:
- main  # Replace with your branch if necessary

pool:
  vmImage: 'windows-latest'  # You can use 'ubuntu-latest' for a Linux agent if preferred

steps:
- script: |
    echo Fetching the latest commit hash...
    git rev-parse HEAD > latest_commit.txt
    set /p latest_commit=<latest_commit.txt
    echo Latest commit hash: %latest_commit%

    echo Running Gitleaks...
    gitleaks detect --commit=%latest_commit%
  displayName: 'Fetch latest commit and run Gitleaks'

  displayName: 'Fetch latest commit and run Gitleaks'
