trigger:
- main  # Adjust as needed

pr:
- '*'

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self  # Checkout the repository

- script: |
    echo "Fetching latest commit from main branch..."
    git fetch origin main
    set latest_commit_on_main=$(git rev-parse origin/main)
    echo "Latest commit on main branch: %latest_commit_on_main%"

    echo "Fetching the parent commit of the latest commit on the PR..."
    git log -n 1 --pretty=format:"%P" > parent_commit.txt
    for /f %%i in (parent_commit.txt) do set parent_commit=%%i
    echo "Parent commit ID: %parent_commit%"

    echo "Running Gitleaks..."
    gitleaks detect --commit=%parent_commit%
  displayName: 'Fetch parent commit and run Gitleaks'
  env:
    GITLEAKS_VERSION: 'latest'
