trigger: none

parameters:
  - name: rules_file
    displayName: "Select Rules File"
    type: string
    default: "Gitleaks/rules1.toml"
    values:
      - "Gitleaks/rulesDNS1.toml"
      - "Gitleaks/rules1.toml"
      - "Gitleaks/rulesDNS3.toml"

  - name: csv_files
    displayName: "Enter Project CSV Files (comma-separated)"
    type: string
    default: "data/14147_Repo1.csv,data/14147_Repo2.csv"

jobs:
- job: GitleaksScan
  displayName: "Run Gitleaks Scan"
  pool:
    vmImage: ubuntu-latest

  steps:
  - checkout: self

  - script: |
      python scan_repos.py --rules ${{ parameters.rules_file }} --csv "${{ parameters.csv_files }}"
    displayName: "Run Gitleaks with dynamic rules and multiple project CSVs"
