trigger:
- main  # or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    echo "##vso[task.setvariable variable=filecount]0"
    i=0
    while IFS= read -r repo; do
      echo "##vso[task.setvariable variable=file_${i}]$repo"
      i=$((i + 1))
    done < file.txt
    echo "##vso[task.setvariable variable=filecount]$i"
  displayName: 'Read repo names from file.txt and set variables'

- ${{ each i in range(0, variables.filecount) }}:
  - template: gitleaks-template.yml
    parameters:
      repoName: ${{ variables['file_' + format('{0}', i)] }}
