trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  REPO_LIST_FILE: 'repo-list.txt'
  GITLEAKS_VERSION: '8.0.0'

stages:
- stage: RunGitleaksScans
  displayName: 'Run Gitleaks Scans for All Repositories'
  jobs:
  - job: ReadRepoList
    displayName: 'Read Repository List'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - script: |
        echo "Reading repository list from $(REPO_LIST_FILE)..."
        REPOS=$(cat $(REPO_LIST_FILE))
        echo "$REPOS" | while read REPO; do
          echo "##vso[task.setvariable variable=REPO_LIST;isOutput=true]$REPO"
        done
      displayName: 'Generate Repository List'
    name: ReadRepoList

  - job: RunGitleaks
    displayName: 'Run Gitleaks Scans'
    dependsOn: ReadRepoList
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - script: |
        REPOS=$(cat $(Build.SourcesDirectory)/$(REPO_LIST_FILE))
        for REPO in $REPOS; do
          echo "Triggering Gitleaks scan for repository: $REPO"
          echo "name: $REPO"
          echo "parameters:"
          echo "  repoName: $REPO"
        done > gitleaks-scan-steps.yml
      displayName: 'Generate Gitleaks Scan Steps'

    - template: gitleaks-scan-steps.yml
