trigger:
- main  # or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    # Read each line in file.txt and create a variable for each file
    while IFS= read -r file; do
      echo "##vso[task.setvariable variable=filelist]$file,$(filelist)"
    done < file.txt
  displayName: 'Prepare file list'

- ${{ each file in variables.filelist.split(',') }}:
  - template: gitleaks-template.yml
    parameters:
      filePath: ${{ file }}
