trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  REPO_LIST_FILE: 'repo-list.txt'
  GITLEAKS_VERSION: '8.0.0'

jobs:
- job: ReadAndRunScans
  displayName: 'Read Repository List and Run Gitleaks Scans'
  steps:
  - script: |
      echo "Reading repository list from $(REPO_LIST_FILE)..."
      REPOS=$(cat $(REPO_LIST_FILE))
      
      # Convert repository names to a format that can be used in YAML conditions
      IFS=$'\n' REPO_ARRAY=($REPOS)
      for REPO in "${REPO_ARRAY[@]}"; do
        echo "##vso[task.setvariable variable=REPO_$REPO;isOutput=true]$REPO"
      done
    displayName: 'Read Repository List'

  - ${{ each repo in variables['REPO_LIST_FILE'].split('\n') }}:
    - script: |
        REPO_NAME=$REPO
        echo "Checking out repository: $REPO_NAME"
        echo "##vso[checkout repository=$REPO_NAME]"
        
        echo "Running Gitleaks on repository: $REPO_NAME"
        docker run --rm -v $(Build.SourcesDirectory)/$REPO_NAME:/repo zricethezav/gitleaks:$(GITLEAKS_VERSION) detect -s /repo
      displayName: 'Run Gitleaks Scan'
      condition: eq(variables['REPO_NAME'], 'true')
