trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  REPO_LIST_FILE: 'repo-list.txt'
  GITLEAKS_VERSION: '8.0.0'

stages:
- stage: ReadRepoList
  displayName: 'Read Repository List and Generate Jobs'
  jobs:
  - job: ReadRepoList
    displayName: 'Read Repository List'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - script: |
        echo "Reading repository list from $(REPO_LIST_FILE)..."
        REPOS=$(cat $(REPO_LIST_FILE))
        
        echo "repositories:"
        echo "$REPOS" | while read REPO; do
          echo "  - $REPO"
        done > repositories.yml
      displayName: 'Generate Repository List'

- stage: RunGitleaksScans
  displayName: 'Run Gitleaks Scans for All Repositories'
  dependsOn: ReadRepoList
  jobs:
  - template: gitleaks-scan-template.yml
    parameters:
      repoName: ${{ each repo in fromYaml('repositories.yml').repositories }}
