trigger:
- main  # or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Adjust as needed

- script: |
    #!/bin/bash

    # Path to the repo.txt file
    repo_file="repo.txt"

    # Directory where reports will be saved
    report_dir="gitleaks-reports"
    mkdir -p "$report_dir"

    # Read each line in repo.txt
    while IFS= read -r folder; do
      # Check if the folder exists
      if [ -d "$folder" ]; then
        # Define the output report file name
        report_file="${report_dir}/$(basename "$folder")-gitleaks-report.json"
        
        # Run Gitleaks scan
        gitleaks detect --source="$folder" --report="$report_file"
        
        echo "Gitleaks report for $folder saved to $report_file"
      else
        echo "Folder $folder does not exist. Skipping."
      fi
    done < "$repo_file"
  displayName: 'Run Gitleaks Scan'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'gitleaks-reports'
    artifact: 'gitleaks-reports'
  displayName: 'Publish Gitleaks Reports'
