trigger:
- none  # Disable triggers for manual runs

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: ReadCSV
  displayName: 'Read CSV and Invoke Template'
  steps:
  - task: Bash@3
    displayName: 'Read CSV and Set Variables'
    inputs:
      targetType: 'inline'
      script: |
        # Define the CSV file path
        csv_file="$(Build.SourcesDirectory)/repos.csv"

        # Prepare an array for job names
        echo "##vso[task.setvariable variable=JobNames;isOutput=true]"

        # Read the CSV file, skipping the header
        while IFS=',' read -r projectName repoName; do
          # Skip the header
          if [[ $projectName != "ProjectName" ]]; then
            echo "Adding job for Project: $projectName, Repo: $repoName"
            echo "##vso[task.setvariable variable=JobNames;isOutput=true]Job_${projectName}_${repoName}"
          fi
        done < <(tail -n +2 "$csv_file")

- ${{ each jobName in parameters.JobNames }}:
  - job: ${{ jobName }}
    displayName: 'Process Repository - ${{ jobName }}'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: my-template.yaml
      parameters:
        projectName: ${{ jobName.split('_')[1] }}  # Extract ProjectName
        repoName: ${{ jobName.split('_')[2] }}     # Extract RepoName
