trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step to download repo and CSV file
- checkout: self

# Step to iterate through the CSV and invoke the Gitleaks template for each repo
- task: Bash@3
  name: GenerateRepoList
  inputs:
    targetType: 'inline'
    script: |
      # Extract the repo list from the CSV and format as YAML for matrix
      echo "repositories:"
      tail -n +2 repo_list.csv | while IFS=, read -r project_name repo_name; do
        echo "- projectName: '$project_name'"
        echo "  repoName: '$repo_name'"
      done > repo_list.yaml

# Include the YAML file with repo list to create the matrix
- task: Bash@3
  name: ReadYAML
  inputs:
    targetType: 'inline'
    script: |
      echo "Reading generated YAML repo list"
      cat repo_list.yaml

# Use the matrix strategy to run Gitleaks for each repo
- template: azure-pipelines-run-gitleaks.yml@templates
  parameters:
    repoListFile: repo_list.yaml
