trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step to download repo and CSV file
- checkout: self

# Step to iterate through the CSV and run the Gitleaks template for each repo
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Read the CSV file and loop through each line (ignoring the header)
      tail -n +2 repo_list.csv | while IFS=, read -r project_name repo_name; do
        echo "Processing project: $project_name, repo: $repo_name"
        
        # Invoke the template for each repository by exporting the variables
        echo "##vso[task.setvariable variable=repoName]$repo_name"
        echo "##vso[task.setvariable variable=projectName]$project_name"
        
        # Call a template for each repo
        echo "Calling Gitleaks template for repo: $repo_name"
        echo "##vso[task.complete result=Succeeded;]"

        # Run the template with the variables set
        azure-pipelines-run-gitleaks.yml
      done
  displayName: 'Iterate CSV and Run Gitleaks Scan for Each Repo'
