trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: ReadCSV
  displayName: 'Read CSV and Generate Job Definitions'
  variables:
    JobDefinitions: ''

  steps:
  - task: Bash@3
    displayName: 'Read CSV and Generate Job Definitions'
    inputs:
      targetType: 'inline'
      script: |
        # Define the CSV file path
        csv_file="$(Build.SourcesDirectory)/repos.csv"

        # Prepare job definitions
        job_defs=""

        # Read the CSV file, skipping the header
        while IFS=',' read -r projectName repoName; do
          # Skip the header
          if [[ $projectName != "ProjectName" ]]; then
            job_defs+="
- job: Process_${projectName}_${repoName}
  displayName: 'Process Repository - ${projectName} - ${repoName}'
  steps:
  - template: my-template.yaml
    parameters:
      projectName: '${projectName}'
      repoName: '${repoName}'
"
          fi
        done < <(tail -n +2 "$csv_file")

        # Set the JobDefinitions variable
        echo "##vso[task.setvariable variable=JobDefinitions;]$job_defs"

- ${{ if ne(variables.JobDefinitions, '') }}:
  ${{ each job in variables.JobDefinitions }}:
  - ${{ job }}
