trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  GITLEAKS_TEMPLATE: 'path/to/your/gitleaks_template.yaml'  # Path to your Gitleaks scan template

jobs:
- job: GitleaksScan
  displayName: 'Run Gitleaks Scan for Repositories'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: ReadCsv@1
    inputs:
      sourcePath: '$(Build.SourcesDirectory)/project_and_repositories.csv'
      outputVariable: 'repositories'

  - ${{ each repo in variables['repositories'] }}:
    - template: ${{ variables.GITLEAKS_TEMPLATE }}
      parameters:
        projectName: ${{ split(repo, ',')[0] }}
        repoName: ${{ split(repo, ',')[1] }}
