trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: ParseRepoList
  steps:
  - checkout: self

  # Parse the CSV and create a variable group of repositories
  - task: Bash@3
    name: ParseRepoList
    inputs:
      targetType: 'inline'
      script: |
        echo "repositories:"
        tail -n +2 repo_list.csv | while IFS=, read -r project_name repo_name; do
          echo "- projectName: '$project_name'"
          echo "  repoName: '$repo_name'"
        done > repo_list.yaml

  # Publish the repo list as an artifact
  - publish: repo_list.yaml
    artifact: repoList

- job: GitleaksScan
  dependsOn: ParseRepoList
  steps:
  - download: current
    artifact: repoList

  # Load the repositories from the parsed YAML
  - task: Bash@3
    name: LoadRepoList
    inputs:
      targetType: 'inline'
      script: |
        REPOS=$(yq eval '.repositories' repo_list.yaml)
        echo "##vso[task.setVariable variable=repos]$REPOS"

  # Use a loop to iterate over repositories
  - ${{ each repo in fromYaml(variables['repos']) }}:
    - template: azure-pipelines-run-gitleaks.yml@templates
      parameters:
        projectName: ${{ repo.projectName }}
        repoName: ${{ repo.repoName }}
