trigger:
- none  # Disable triggers for manual runs

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: ReadCSV
  displayName: 'Read CSV and Set Job Names'
  variables:
    JobNames: ''

  steps:
  - task: Bash@3
    displayName: 'Read CSV and Set Variables'
    inputs:
      targetType: 'inline'
      script: |
        # Define the CSV file path
        csv_file="$(Build.SourcesDirectory)/repos.csv"
        
        # Read the CSV file, skipping the header
        while IFS=',' read -r projectName repoName; do
          # Skip the header
          if [[ $projectName != "ProjectName" ]]; then
            echo "Adding job for Project: $projectName, Repo: $repoName"
            echo "##vso[task.setvariable variable=JobNames;isOutput=true]Job_${projectName}_${repoName}"
          fi
        done < <(tail -n +2 "$csv_file")

- ${{ if ne(variables.JobNames, '') }}:
  ${{ each job in variables.JobNames.split(';') }}:
  - job: ${{ job }}
    displayName: 'Process Repository - ${{ job }}'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: my-template.yaml
      parameters:
        projectName: ${{ job }}  # Assuming you can derive projectName from the job name
        repoName: ${{ job }}      # Adjust this based on your requirements
