trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Step 1: Read CSV and loop through each row
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Import the CSV file located in the source directory
      $csv = Import-Csv $(Build.SourcesDirectory)/repos.csv
      
      # Initialize an empty array for parameters
      $repoParams = @()

      # Loop through each row and add the parameters to the array
      foreach ($row in $csv) {
          $repoParams += @{
              projectName = $row.ProjectName
              repoName    = $row.RepoName
          }
      }

      # Serialize the array as JSON to pass it to the next step
      $json = $repoParams | ConvertTo-Json -Compress
      Write-Host "##vso[task.setvariable variable=repoParams]$json"

# Step 2: Iterate over the array of repo parameters and invoke the template
- ${{ each repo in fromJson(variables['repoParams']) }}:
  - template: my-template.yaml
    parameters:
      projectName: ${{ repo.projectName }}
      repoName: ${{ repo.repoName }}
