trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Step 1: Use Bash to read the CSV and loop through each row
- task: Bash@3
  displayName: 'Read CSV and set variables'
  inputs:
    targetType: 'inline'
    script: |
      # Define the CSV file path
      csv_file="$(Build.SourcesDirectory)/repos.csv"

      # Read the CSV file, skipping the header (ProjectName,RepoName)
      tail -n +2 "$csv_file" | while IFS=',' read -r project repo; do
        echo "Processing Project: $project, Repo: $repo"

        # Set pipeline variables for the current row
        echo "##vso[task.setvariable variable=ProjectName]$project"
        echo "##vso[task.setvariable variable=RepoName]$repo"

        # Call the next template with these variables
        echo "Calling template for ProjectName: $project, RepoName: $repo"

        # Call the next template or step
        echo "##vso[task.setvariable variable=RepoProcessed]true"

      done

# Step 2: Dynamically invoke the template for each row in the CSV
- template: my-template.yaml
  parameters:
    projectName: $(ProjectName)
    repoName: $(RepoName)
